using System;using System.Diagnostics;using System.Management;using Microsoft.Win32;using SOACS.Arsenal.Models;
namespace SOACS.Arsenal.Services
{
 public class MachineQualificationService
 {
  public MachineQualification Assess(){var q=new MachineQualification();try{using(var s=new ManagementObjectSearcher("SELECT Manufacturer,Model FROM Win32_ComputerSystem"))foreach(ManagementObject m in s.Get()){q.Manufacturer=Convert.ToString(m["Manufacturer"]);q.Model=Convert.ToString(m["Model"]);break;}using(var s=new ManagementObjectSearcher("SELECT SMBIOSBIOSVersion FROM Win32_BIOS"))foreach(ManagementObject m in s.Get()){q.BiosVersion=Convert.ToString(m["SMBIOSBIOSVersion"]);break;}q.PowerStatus=System.Windows.Forms.SystemInformation.PowerStatus.PowerLineStatus.ToString();var bat=System.Windows.Forms.SystemInformation.PowerStatus.BatteryLifePercent;q.BatteryStatus=bat<0?"Not reported":Math.Round(bat*100)+"%";q.PendingReboot=IsPendingReboot()?"YES":"NO";q.BitLockerStatus=GetBitLockerStatus();bool ac=q.PowerStatus=="Online"||q.PowerStatus=="Unknown";bool battery=bat<0||bat>=0.40f;q.FirmwareReady=ac&&battery&&!IsPendingReboot();q.OverallStatus=q.FirmwareReady?"READY FOR FIRMWARE REVIEW":"NOT READY FOR FIRMWARE";q.Details="AC power: "+q.PowerStatus+" | Battery: "+q.BatteryStatus+" | Pending reboot: "+q.PendingReboot+" | BitLocker: "+q.BitLockerStatus;}catch(Exception ex){q.OverallStatus="QUALIFICATION INCOMPLETE";q.FirmwareReady=false;q.Details=ex.Message;}return q;}
  static bool IsPendingReboot(){return Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending")!=null||Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired")!=null;}
  static string GetBitLockerStatus(){try{var p=Process.Start(new ProcessStartInfo("manage-bde.exe","-status C:"){UseShellExecute=false,RedirectStandardOutput=true,CreateNoWindow=true});string t=p.StandardOutput.ReadToEnd();p.WaitForExit(10000);if(t.IndexOf("Protection On",StringComparison.OrdinalIgnoreCase)>=0)return "Protection On";if(t.IndexOf("Protection Off",StringComparison.OrdinalIgnoreCase)>=0)return "Protection Off";return "Unknown";}catch{return "Unavailable";}}
 }
}
