using System;using System.Collections.Generic;using System.IO;using System.Linq;using System.Security.Cryptography;using System.Text.RegularExpressions;using System.Xml.Linq;using SOACS.Arsenal.Models;
namespace SOACS.Arsenal.Services
{
 public class HashValidationService
 {
  readonly string _repository; readonly Dictionary<string,string> _manifest=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase); bool _manifestMalformed;
  public HashValidationService(string repository){_repository=repository;LoadCentralManifests();}
  public void Validate(PatchItem p){string expected=null;bool malformed=false;FindSidecar(p.FullPath,out expected,out malformed);if(expected==null&&!malformed)expected=FindManifest(p);p.HashProvided=expected!=null||malformed;p.ExpectedHash=expected??"";if(malformed){p.HashStatus="Invalid Manifest";p.HashValid=false;return;}if(expected==null){p.HashStatus=_manifestMalformed?"Invalid Manifest":"Not Provided";p.HashValid=!_manifestMalformed;return;}p.CalculatedHash=ComputeSha256(p.FullPath);p.HashValid=string.Equals(Normalize(expected),Normalize(p.CalculatedHash),StringComparison.OrdinalIgnoreCase);p.HashStatus=p.HashValid?"Verified":"Mismatch";}
  static string ComputeSha256(string path){using(var s=File.OpenRead(path))using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(s)).Replace("-","");}
  void FindSidecar(string file,out string hash,out bool malformed){hash=null;malformed=false;var candidates=new[]{file+".sha256",file+".sha256.txt",file+".hash",Path.ChangeExtension(file,".sha256")};foreach(var c in candidates.Distinct(StringComparer.OrdinalIgnoreCase)){if(!File.Exists(c))continue;var text=File.ReadAllText(c);hash=ExtractHash(text);if(hash==null)malformed=true;return;}}
  string FindManifest(PatchItem p){string relative="";try{relative=Path.GetFullPath(p.FullPath).Substring(Path.GetFullPath(_repository).TrimEnd(Path.DirectorySeparatorChar).Length).TrimStart(Path.DirectorySeparatorChar);}catch{}string h;if(_manifest.TryGetValue(relative,out h))return h;if(_manifest.TryGetValue(p.FileName,out h))return h;return null;}
  void LoadCentralManifests(){foreach(var name in new[]{"PatchManifest.xml","Hashes.xml"}){var path=Path.Combine(_repository,name);if(!File.Exists(path))continue;try{var doc=XDocument.Load(path);foreach(var p in doc.Descendants("Package")){var f=(string)p.Element("File")??(string)p.Attribute("File");var h=(string)p.Element("Hash")??(string)p.Attribute("Hash");Add(f,h);}}catch{_manifestMalformed=true;}}foreach(var name in new[]{"SHA256SUMS.txt","Hashes.csv"}){var path=Path.Combine(_repository,name);if(!File.Exists(path))continue;try{foreach(var line in File.ReadAllLines(path)){if(string.IsNullOrWhiteSpace(line)||line.TrimStart().StartsWith("#"))continue;var h=ExtractHash(line);if(h==null){if(line.IndexOf("hash",StringComparison.OrdinalIgnoreCase)<0)_manifestMalformed=true;continue;}var remainder=line.Replace(h,"").Trim(' ', '\t', ',', '*', '"');if(remainder.Contains(","))remainder=remainder.Split(',').Last().Trim(' ', '"');Add(remainder,h);}}catch{_manifestMalformed=true;}}}
  void Add(string f,string h){h=Normalize(h);if(string.IsNullOrWhiteSpace(f)||h==null){_manifestMalformed=true;return;}_manifest[f.Replace('/',Path.DirectorySeparatorChar)]=h;_manifest[Path.GetFileName(f)]=h;}
  static string ExtractHash(string text){var m=Regex.Match(text??"",@"(?i)(?<![0-9a-f])[0-9a-f]{64}(?![0-9a-f])");return m.Success?m.Value:null;}
  static string Normalize(string h){if(string.IsNullOrWhiteSpace(h))return null;var x=Regex.Replace(h,@"[^0-9A-Fa-f]","");return x.Length==64?x.ToUpperInvariant():null;}
 }
}
